# Generated by Django 5.0 on 2023-12-15 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('item_id', models.TextField(primary_key=True, serialize=False)),
                ('item_description', models.TextField()),
                ('item_state', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on_loan', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('loan_is_finished', models.BooleanField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='overview.items')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'loans',
            },
        ),
    ]
